<?php 

// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.

/* CONFIG ----------------------------------------------------------------------------------------------------------- */

$resolutions   = array(1024, 600, 320); // the resolution break-points to use (screen widths, in pixels)
$cache_dir     = "cache-ai";            // where to store the generated re-sized images.
$jpg_quality   = 60;                    // the quality of any generated JPGs on a scale of 0 to 100
$sharpen       = TRUE;                  // Shrinking images can blur details, perform a sharpen on re-scaled images?
$watch_cache   = TRUE;                  // check that the adapted image isn't stale (ensures updated source images are re-cached)
$browser_cache = 60*60*24*7;            // How long the BROWSER cache should last (seconds, minutes, hours, days. 7days by default)

/* END CONFIG --------------------------------------------------------------------------------------------------------*/

// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.

?>