<?php 

// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.

/* CONFIG ----------------------------------------------------------------------------------------------------------- */

/**
 * Yes, the following is PHP code...
 * We will make it more user friendly in the future.
 * Promise!
 */

// the resolution breakpoints of screens widths in pixels
$resolutions = array( 1024, 600, 320 ); 

// where to store the generated resized images
$cache_dir = "cache-ai";

// the quality of any generated JPGs (from 0 to 100)
$jpg_quality = 60;

// perform a sharpen on rescaled images to reduce blur
$sharpen = TRUE;

// check that a resized image isn't stale 
$watch_cache = TRUE;

// how long the browser cache should last (s*m*h*d)
$browser_cache = 60*60*24*7;

/* END CONFIG --------------------------------------------------------------------------------------------------------*/

// DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.

?>