<?php 

    //##############################################################################################//
    //                                                                                              //
    //  DO NOT EDIT THIS FILE MANUALLY. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.  //
    //                                                                                              //

        // Device widths resolutions. 

        $resolutions = array( 1024, 640, 480 ); 

        // The directory of the images cache. 

        $cache_dir = "cache/adaptive-images"; 

        // JPEG quality of resized images. 

        $jpg_quality = 65; 

        // Sharpen resized images. 

        $sharpen = TRUE; 

        // Check for new versions of cached images. 

        $watch_cache = TRUE; 

        // Browser cache duration for images. 

        $browser_cache = 60 * 60 * 24 * 180; 

    //                                                                                              //
    //  DO NOT EDIT THIS FILE MANUALLY. IT IS AUTOMATICALLY GENERATED BY THE PLUGIN SETTINGS PAGE.  //
    //                                                                                              //
    //==============================================================================================//

?>